spring.application.name=ProjetoWebRpg
spring.datasource.url=jdbc:mysql://localhost:3306/gerenciamento_habilidades
spring.datasource.username=root

spring.jpa.hibernate.ddl−auto=none
spring.jpa.show−sql=true
spring.jpa.database−platform=org.hibernate.dialect.MySQLDialect